### ISSUE TITLE
插件于系统功能有冲突

### ISSUE THREAD

**Issue by herbieliang** [xiaoxuan6/login-captcha#1]
开启插件后，会导致覆盖视图模板路径功能失效，同时和xiaoxuan6/login这个扩展也有冲突，会导致该插件失效。

**Comment by xiaoxuan6** [comment]
login-captcha这个是没有问题的，xiaoxuan6/login会和login-captcha有冲突，应为两个都关于登录，修改的方法是同一个，等我有时间更新一下，这两个的合并的代码

**Comment by onetreegrow** [comment]
开启插件后，会导致覆盖视图模板路径功能失效,这个问题修复了吗
