### ISSUE TITLE
如何自定义登录 HTML 代码？

### ISSUE THREAD

**Issue by yeehooZen** [xiaoxuan6/login-captcha#11]
vendor\james.xue\login-captcha\resources\views\index.blade.php
如何在项目里覆盖这个文件？

之前我在 app\Admin\bootstrap.php 里 写
app('view')->prependNamespace('admin', resource_path('views/laravel-admin'));

然后创建文件 resources\views\laravel-admin\login.blade.php

用了这个插件后 resources\views\laravel-admin\login.blade.php 没用了

感谢～

**Comment by xiaoxuan6** [comment]
目前还不能自定义页面，只能使用包中的页面，等下一个版本吧

**Comment by yeehooZen** [comment]
> 目前还不能自定义页面，只能使用包中的页面，等下一个版本吧

感谢，惭愧 我研究了下。还是没想到可以自定义的方法 我直接改了包里的文件
