### ISSUE TITLE
老是验证失败，提示验证码错误，怎么都输不对？

### ISSUE THREAD

**Issue by huaxiuyiwei** [xiaoxuan6/login-captcha#12]

**Comment by xiaoxuan6** [comment]
> _No description provided._

你的 laravel 版本和 laravel-admin 以及 login-captcha 和 php 版本分别是多少？看一下自己的版本有问题吗

**Comment by lizhi9527** [comment]
> > _No description provided._
> 
> 你的 laravel 版本和 laravel-admin 以及 login-captcha 和 php 版本分别是多少？看一下自己的版本有问题吗

我也有这种问题   刷新页面怎么都不行  刷新验证码可以     php:7.2 laravel-admin:1.7   login-captcha:2.0

**Comment by wenteng123** [comment]
前端怎么获取验证码
