### ISSUE TITLE
退出登录后验证码填写正确也一直报错

### ISSUE THREAD

**Issue by cwbiao** [xiaoxuan6/login-captcha#4]
输入：![image](https://user-images.githubusercontent.com/13530884/55529414-e6b1a200-56d3-11e9-9c29-e53d4a82dbbd.png) 
提示：
![image](https://user-images.githubusercontent.com/13530884/55529427-f6c98180-56d3-11e9-91a8-16c78894c720.png)

**Comment by xiaoxuan6** [comment]
你用的laravel-admin版本是1.6.10会包这个错误，待修复，目前仅支持小于1.6.10版本
