### ISSUE TITLE
验证码开关设置为false没有效果

### ISSUE THREAD

**Issue by linxbin** [xiaoxuan6/login-captcha#9]
james.xue/login-captcha :1.8.1
laravel-admin:1.7.2
laravel:5.8.14

在admin.php中，修改
```
'extensions'                => [
        'login-captcha' => [
            // set to false if you want to disable this extension
            'enable' => false,
        ]
```
登录页面的验证码依旧存在

**Comment by xiaoxuan6** [comment]
> james.xue/login-captcha :1.8.1
> laravel-admin:1.7.2
> laravel:5.8.14
> 
> 在admin.php中，修改
> 
> ```
> 'extensions'                => [
>         'login-captcha' => [
>             // set to false if you want to disable this extension
>             'enable' => false,
>         ]
> ```
> 
> 登录页面的验证码依旧存在

![image](https://user-images.githubusercontent.com/32762220/63594762-ec0f7a80-c5e9-11e9-8e0a-533728dfb1df.png)

更新到1.8.2
